### ISSUE TITLE
Washington Post Paywall Is Now Appearing

### ISSUE THREAD

**Issue by jameshfischer** [marcopaone/Extreme-Paywall-Bypasser#1]
Wapo.com has made some sort of enhancement to their paywall.
No bypass no more.

**Comment by FacelookHK** [comment]
Use "Bypass Paywalls Clean" on Firefox, it works perfectly.

**Comment by Andrew3000s** [comment]
There is no longer any possibility of upgrading the extension.
Edge's new policies block extensions that can bypass paywalls.

**Comment by jameshfischer** [comment]
So, I guess we have to blame Edge browser, and close this issue
